In [7]:
import cv2
import numpy as np

In [9]:
img = cv2.imread('RGB.jpg')
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

lower_red=np.array([160,110,170])
upper_red=np.array([180,255,255])
maskR = cv2.inRange(hsv,lower_red,upper_red)
res = cv2.bitwise_and(img,img,mask=maskR)
gray = cv2.cvtColor(res,cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(gray,1,1,cv2.THRESH_TOZERO)
image,contours,hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
cnt = contours[0]
#M = cv2.moments(cnt)
ellipse = cv2.fitEllipse(cnt)
#print(M)
print("*****************")
print(cnt)
print(ellipse)
print(contours)

*****************
[[[160 160]]

 [[160 161]]

 [[160 162]]

 [[160 163]]

 [[161 162]]

 [[161 161]]

 [[161 160]]]
((160.5, 161.2857208251953), (0.0, 1.0), 0.0)
[array([[[160, 160]],

       [[160, 161]],

       [[160, 162]],

       [[160, 163]],

       [[161, 162]],

       [[161, 161]],

       [[161, 160]]], dtype=int32), array([[[128, 160]],

       [[129, 160]],

       [[130, 160]],

       [[131, 160]],

       [[132, 160]],

       [[133, 160]],

       [[134, 160]],

       [[135, 160]],

       [[136, 160]],

       [[137, 160]],

       [[138, 160]],

       [[139, 160]],

       [[140, 160]],

       [[141, 160]],

       [[142, 160]],

       [[143, 160]],

       [[142, 160]],

       [[141, 160]],

       [[140, 160]],

       [[139, 160]],

       [[138, 160]],

       [[137, 160]],

       [[136, 160]],

       [[135, 160]],

       [[134, 160]],

       [[133, 160]],

       [[132, 160]],

       [[131, 160]],

       [[130, 160]],

       [[129, 160]]], dtype=int

In [3]:
cx = int(M['m10']/(2*M['m00']))
cy = int(M['m01']/(2*M['m00']))

NameError: name 'M' is not defined

In [4]:
(x,y),(MA,ma),angle = ellipse

In [5]:
cv2.circle(img,(int(x),int(y)),1,(255,255,255),-1)

array([[[ 0,  0, 15],
        [ 0,  0, 13],
        [ 0,  0,  8],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  7],
        [ 0,  0,  6],
        [ 0,  0,  3],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 2,  2,  0],
        [ 2,  2,  0],
        [ 2,  2,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ...,

       [[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        ...,
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        ...,
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        ...,
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 5,  5,  5]]], dtype=uint8)

In [6]:
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()