In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread("RGB.jpg")

## 图片蒙版

In [3]:
cv2.imshow("img",img)

mask = np.zeros(img.shape[:2],dtype="uint8")
(cx,cy) = (img.shape[1]//2,img.shape[0]//2)
cv2.rectangle(mask,(cx-250,cy-150),(cx+200,cy+150),255,-1)
cv2.imshow("Mask",mask)

masked = cv2.bitwise_and(img,img,mask=mask)
cv2.imshow("Masked",masked)
cv2.waitKey(0)

-1

In [4]:
mask = np.zeros(img.shape[:2],dtype="uint8")
cv2.circle(mask,(cx,cy),100,255,-1)
masked = cv2.bitwise_and(img,img,mask=mask)
cv2.imshow("Mask",mask)
cv2.imshow("Masked",masked)
cv2.waitKey(0)

-1

## BGR三通道分割
拆分图像颜色通道使用cv2.split(image)方法

合并 使用 cv2.merge([B,G,R]) 方法
***

In [5]:
(B,G,R) = cv2.split(img)
cv2.imshow("Blue",B)
cv2.imshow("Green",G)
cv2.imshow("Red",R)

merged = cv2.merge([B,G,R])
cv2.imshow("Merged",merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

zeros = np.zeros(img.shape[:2],dtype="uint8")
cv2.imshow("red",cv2.merge([zeros,zeros,R]))
cv2.imshow("blue",cv2.merge([B,zeros,zeros]))
cv2.imshow("green",cv2.merge([zeros,G,zeros]))
cv2.waitKey(0)
cv2.destroyAllWindows()
# 为了显示频道的实际“颜色”，我们首先需要使用cv2.split来分割图像。
# 然后，我们需要重新构建图像，
# 但这次设置所有像素为0，除了当前通道

In [6]:
B

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 2, 2, ..., 0, 0, 0],
       ..., 
       [1, 1, 1, ..., 4, 5, 5],
       [1, 1, 1, ..., 4, 5, 5],
       [1, 1, 1, ..., 4, 5, 5]], dtype=uint8)

In [7]:
G

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 2, 2, ..., 0, 0, 0],
       ..., 
       [1, 1, 1, ..., 4, 5, 5],
       [1, 1, 1, ..., 4, 5, 5],
       [1, 1, 1, ..., 4, 5, 5]], dtype=uint8)

In [8]:
R

array([[15, 13,  8, ...,  0,  0,  0],
       [ 7,  6,  3, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 1,  1,  1, ...,  4,  5,  5],
       [ 1,  1,  1, ...,  4,  5,  5],
       [ 1,  1,  1, ...,  4,  5,  5]], dtype=uint8)

In [9]:
B.shape

(179, 494)

In [10]:
B.max()

255